/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rr.authadi.client

import kotlinx.coroutines.*
import com.rr.proto.authadi.UserImmigrationGrpc
import com.rr.proto.authadi.UserImmigrationRequest
import com.rr.proto.authadi.addUserIdentity
import io.grpc.ManagedChannelBuilder
import java.util.*

class App {
    fun insertUserIdentity() {
        val localhost = ManagedChannelBuilder.forAddress("localhost", 5987)
                .usePlaintext().build()
        val immigration = UserImmigrationGrpc.newStub(localhost)
        val requestBuilder = UserImmigrationRequest.newBuilder()
        requestBuilder.userKey = "johndoe@mailserver.com"
        requestBuilder.userReferenceId = UUID.randomUUID().toString()
        requestBuilder.password = "SecretPassword!"
        requestBuilder.active = true
        val request = requestBuilder.build()
        runBlocking {
            val response = immigration.addUserIdentity(request)
            println(response)
        }
    }
}

fun main(args: Array<String>) {
    App().insertUserIdentity()
}
