/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rr.authadi.client

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTest {
    @Test fun testAppHasAGreeting() {
        assertTrue(true)
    }
}
